build: off
clone_depth: 5
configuration: Release

environment:
  PKG_NAME: liknorm
  CIBW_BEFORE_BUILD_WINDOWS: powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/limix/liknorm/master/install.bat', 'install-liknorm.bat')" && install-liknorm.bat
  matrix:
    - platform: x64
      ARCH: x64
      PYTHON: C:\Python36-x64
      CIBW_SKIP: cp27-* cp33-* cp34-* cp35-* *-win32
    - platform: x86
      ARCH: x86
      PYTHON: C:\Python36
      CIBW_SKIP: cp27-* cp33-* cp34-* cp35-* *-win_amd64

install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/limix/liknorm/master/install.bat', 'install-liknorm.bat')" && install-liknorm.bat
  - set PATH=%programfiles%\liknorm\bin;%PATH%
  - python -c "import ctypes; ctypes.CDLL('liknorm.dll')"
  - set LIBRARY_INC=%programfiles%\liknorm\include;%LIBRARY_INC%
  - set LIBRARY_LIB=%programfiles%\liknorm\lib;%LIBRARY_LIB%
  - "%PYTHON%\\python.exe -m pip install cibuildwheel>=0.9.1"

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - python -m pip install -U setuptools pip pytest pytest-pycodestyle -q
  - dir liknorm
  - python --version
  - python -c "import ctypes; ctypes.CDLL('liknorm.dll')"
  # - python -c "import ctypes; ctypes.CDLL('liknodqwdqwrm.dll')"
  - where pytest*
  - python -m pip install -U cffi pytest pytest-runner numpy -q
  - python setup.py test
  # - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/horta/ci/master/appveyor.bat', 'appveyor.bat')" && appveyor.bat
  # - "%PYTHON%\\python.exe -m cibuildwheel --output-dir wheelhouse"
  # - if [%APPVEYOR_REPO_TAG%]==[true] (%PYTHON%\python.exe -m pip install twine && %PYTHON%\python.exe -m twine upload --skip-existing wheelhouse/*)

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels