build: off
clone_depth: 5
platform: x64
configuration: Release

environment:
    PKG_NAME: liknorm
    PYTHON: "C:\\Python36-x64"

install:
    - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/limix/hcephes/master/install.bat', 'install-hcephes.bat')" && install-hcephes.bat
    - set PATH=%programfiles%\liknorm\bin;%PATH%
    - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/limix/liknorm/master/install.bat', 'install-liknorm.bat')" && install-liknorm.bat
    - set PATH=%programfiles%\liknorm\bin;%PATH%
    - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/horta/ci/master/appveyor.bat', 'appveyor.bat')" && appveyor.bat
