python: 3.7
env:
  global:
    - PKG_NAME=liknorm
    - CIBW_SKIP="cp27-* cp34-* cp35-* *i686*"
    - CIBW_BEFORE_BUILD_LINUX="bash ci/before-build-linux"
    - CIBW_BEFORE_BUILD_MACOS="bash ci/before-build-macos"
    - CIBW_BEFORE_BUILD_WINDOWS="bash ci/before-build-windows"
    - CIBW_TEST_COMMAND="python -c \"import $PKG_NAME; import sys; sys.exit($PKG_NAME.test())\""
matrix:
  include:
    - os: linux
      sudo: required
      services: docker
      before_install:
        - curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=logaddexp DO_CMD=sudo bash
        - curl -fsSL https://git.io/JerYI | GITHUB_USER=limix GITHUB_PROJECT=liknorm DO_CMD=sudo bash
    - os: osx
      language: shell
      before_install:
        - ln -s $(brew --prefix)/bin/python3 $(brew --prefix)/bin/python
        - ln -s $(brew --prefix)/bin/pip3 $(brew --prefix)/bin/pip
        - hash -r
        - python -m pip install --upgrade pip setuptools
        - curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=logaddexp DO_CMD=sudo bash
        - curl -fsSL https://git.io/JerYI | GITHUB_USER=limix GITHUB_PROJECT=liknorm DO_CMD=sudo bash
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        - curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=logaddexp bash
        - curl -fsSL https://git.io/JerYI | GITHUB_USER=limix GITHUB_PROJECT=liknorm bash
addons:
  apt:
    packages:
      - libffi-dev
      - libffi6
      - cmake
install:
  - curl -fsSL $URL/travis-check-readme.sh | bash
  - curl -fsSL $URL/travis-py-min-deps.sh | bash
  - curl -fsSL $URL/travis-py-check-style.sh | bash
  - curl -fsSL $URL/travis-py-check-black.sh | bash
  - curl -fsSL $URL/travis-py-dev-test.sh | bash
  - curl -fsSL $URL/travis-py-install-test.sh | bash
script:
  - curl -fsSL $URL/travis-py-sdist-test.sh | bash
  - git clean -xdf
  - python -m pip install cibuildwheel>=1.1.0
  - cibuildwheel --output-dir wheelhouse
  - |
    if [ "${TRAVIS_TAG:-}" != "" ]; then
      python -m pip install twine
      python -m twine upload --skip-existing wheelhouse/*
    fi
  - git clean -xdf
notifications:
  email:
    recipients:
      - danilo.horta@pm.me
    on_success: never
    on_failure: always
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: fMasPDnDnJOgzbgS+UcNTvykBhTQxsAXm2aCdSB1W9XM3f98+Qlmd1w0jbDrljkCo+e1trnZDn+eW0fW4h+oX7FdlwAM1ktOJVJJI1wNq/xai8q5a4NAtY/us8OKF5sg2UfyuuPXm6P4dhdW9minbTJ3bmh+n7IftrVYwFf8gSBAg6OEN07NrAQzHOb05Jkcop6d1JDjzperVWyc/0GwVSZN+vx5Z1eBk6uVFffNSXduZvn1ykqv7a6rw/n+PDQK9Dzpwn+OqFv407uoMcORxPDYJBFb3KRXPnZNSmtbDQsAxbgoa5HDFmEELpQoDf3eWqFYG9LxS3fVSPTn0pyObx+hNXUFvKXdouYnGi19yHULVFWLCjGXSwL2OwXDOkQlPi4pOR73RlwU/T71qfzPmivVpcAYZrV+/c7ljL8vfGqVQpgOJRzo5fmI7NXd26FIHcf4O1NVeL763v0LTVGnTjutm2mdwZJbez6R6aIyDnzOIeXtZ4uiFwjnXaS4HKGRFvKHld4Q7SgjzDpj1I6OgQufh4/7mulFWnbjgZVVzDWW3OhHKR3bG7CrP0kJCD4y6WX1rMVtsl4aZgnCLFDV9xOiH/diSx2vIbP+zR4W0VXu/1xIrqVNGdodq7hjbUtvdbRPMqwvNnk2ymCtT/u7cNjYe74alHG2y8+8WBe/UGg=
  on:
    tags: true
    repo: limix/liknorm-py
    branch: master
    python: 3.6
