os: linux
language: python
sudo: false
python: 3.6
env:
  - PKG_NAME=liknorm
addons:
  apt:
    packages:
        - pandoc
        - libffi-dev
        - libffi6
install:
    - bash <(curl -fsSL https://raw.githubusercontent.com/limix/hcephes/master/install)
    - bash <(curl -fsSL https://raw.githubusercontent.com/limix/liknorm/master/install)
script:
    - bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis.sh)
notifications:
  email:
    recipients:
    - danilo.horta@gmail.com
    on_success: never
    on_failure: always
