language: python
python: 3.6
env:
  global:
  - PKG_NAME=liknorm
  - CIBW_SKIP="cp27-* cp34-* cp35-* *i686*"
  - CIBW_BEFORE_BUILD_LINUX="bash before-build-linux"
  - CIBW_BEFORE_BUILD_MACOS="curl -O https://raw.githubusercontent.com/limix/liknorm/master/install && bash install"
  - CIBW_TEST_COMMAND="python -c \"import $PKG_NAME; import sys; sys.exit($PKG_NAME.test())\""
matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx
      language: generic
      before_install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew unlink python2
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install python3
        - export PATH=$(brew --prefix)/bin:$(brew --prefix)/sbin:$PATH
        - ln -s $(brew --prefix)/bin/python3 $(brew --prefix)/bin/python
        - ln -s $(brew --prefix)/bin/pip3 $(brew --prefix)/bin/pip
        - hash -r
        - python -m pip install --upgrade pip setuptools wheel
addons:
  homebrew:
    packages:
    - python
    - pip
    update: true
  apt:
    packages:
    - libffi-dev
    - libffi6
    - cmake
install:
- bash <(curl -fsSL https://raw.githubusercontent.com/limix/liknorm/master/install)
script:
- |
  if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
    sudo mkdir -p /usr/local/man
    sudo chown -R "${USER}:admin" /usr/local/man
  fi
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis.sh) || exit 1
- python -m pip install cibuildwheel>=0.9.2
- cibuildwheel --output-dir wheelhouse
- |
  if [ "${TRAVIS_TAG:-}" != "" ]; then
    python -m pip install twine
    python -m twine upload --skip-existing wheelhouse/*
  fi
notifications:
  email:
    recipients:
    - danilo.horta@pm.me
    on_success: never
    on_failure: always
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: fMasPDnDnJOgzbgS+UcNTvykBhTQxsAXm2aCdSB1W9XM3f98+Qlmd1w0jbDrljkCo+e1trnZDn+eW0fW4h+oX7FdlwAM1ktOJVJJI1wNq/xai8q5a4NAtY/us8OKF5sg2UfyuuPXm6P4dhdW9minbTJ3bmh+n7IftrVYwFf8gSBAg6OEN07NrAQzHOb05Jkcop6d1JDjzperVWyc/0GwVSZN+vx5Z1eBk6uVFffNSXduZvn1ykqv7a6rw/n+PDQK9Dzpwn+OqFv407uoMcORxPDYJBFb3KRXPnZNSmtbDQsAxbgoa5HDFmEELpQoDf3eWqFYG9LxS3fVSPTn0pyObx+hNXUFvKXdouYnGi19yHULVFWLCjGXSwL2OwXDOkQlPi4pOR73RlwU/T71qfzPmivVpcAYZrV+/c7ljL8vfGqVQpgOJRzo5fmI7NXd26FIHcf4O1NVeL763v0LTVGnTjutm2mdwZJbez6R6aIyDnzOIeXtZ4uiFwjnXaS4HKGRFvKHld4Q7SgjzDpj1I6OgQufh4/7mulFWnbjgZVVzDWW3OhHKR3bG7CrP0kJCD4y6WX1rMVtsl4aZgnCLFDV9xOiH/diSx2vIbP+zR4W0VXu/1xIrqVNGdodq7hjbUtvdbRPMqwvNnk2ymCtT/u7cNjYe74alHG2y8+8WBe/UGg=
  on:
    tags: true
    repo: limix/liknorm-py
    branch: master
    python: 3.6
