env:
  global:
    - URL=https://raw.githubusercontent.com/horta/ci/master
    - PKG_NAME=liknorm
    - CIBW_SKIP="cp27-* cp34-* cp35-* *i686*"
    - CIBW_BEFORE_BUILD_LINUX="bash ci/before-build-linux"
    - CIBW_BEFORE_BUILD_MACOS="bash ci/before-build-macos"
    - CIBW_BEFORE_BUILD_WINDOWS="bash ci/before-build-windows"
    - CIBW_TEST_COMMAND="python3 -c \"import $PKG_NAME; import sys; sys.exit($PKG_NAME.test())\""
matrix:
  include:
    - os: linux
      dist: bionic
      language: python
      services: docker
      # env:
      #   - LIKNORM_INCLUDE_DIRS=/usr/local/include
      #   - LIKNORM_LIBRARY_DIRS=/usr/local/lib
      #   - LIKNORM_EXTRA_LINK_ARGS="-Wl,-rpath,/usr/local/lib"
      before_install:
        - curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=logaddexp bash
        - curl -fsSL https://git.io/JerYI | GITHUB_USER=limix GITHUB_PROJECT=liknorm bash
    - os: osx
      language: shell
      before_install:
        - python3 -m pip install --upgrade pip setuptools
        - curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=logaddexp bash
        - curl -fsSL https://git.io/JerYI | GITHUB_USER=limix GITHUB_PROJECT=liknorm bash
    # - os: windows
    #   language: shell
    #   before_install:
    #     - choco install python --version 3.8.0
    #     - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
    #     - cp /c/Python38/python.exe /c/Python38/python3.exe
    #     - export CMAKE_PREFIX_PATH="/c/Program Files"
    #     - curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=logaddexp INSTALL_PREFIX="$CMAKE_PREFIX_PATH/logaddexp" bash
    #     - curl -fsSL https://git.io/JerYI | GITHUB_USER=limix GITHUB_PROJECT=liknorm INSTALL_PREFIX="$CMAKE_PREFIX_PATH/liknorm" bash
    #     - cp "$CMAKE_PREFIX_PATH/liknorm/bin/liknorm.dll" liknorm/
addons:
  apt:
    packages:
      - libffi-dev
      - libffi6
      - cmake
install:
  - curl -fsSL $URL/check-readme.sh | bash
  - curl -fsSL $URL/py-min-deps.sh | bash
  - curl -fsSL $URL/py-check-style.sh | bash
  - curl -fsSL $URL/py-dev-test.sh | bash
  # - curl -fsSL $URL/py-import-time.sh | bash
  # - curl -fsSL $URL/py-sdist-test.sh | bash
  # - git clean -xdf
  # - python3 -m pip install cibuildwheel>=1.1.0
# script:
  # - cibuildwheel --output-dir wheelhouse
  # - |
  #   if [ "${TRAVIS_TAG:-}" != "" ]; then
  #     python3 -m pip install twine
  #     python3 -m twine upload --skip-existing wheelhouse/*
  #   fi
  # - git clean -xdf
notifications:
  email:
    recipients:
      - danilo.horta@pm.me
    on_success: never
    on_failure: always
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: fMasPDnDnJOgzbgS+UcNTvykBhTQxsAXm2aCdSB1W9XM3f98+Qlmd1w0jbDrljkCo+e1trnZDn+eW0fW4h+oX7FdlwAM1ktOJVJJI1wNq/xai8q5a4NAtY/us8OKF5sg2UfyuuPXm6P4dhdW9minbTJ3bmh+n7IftrVYwFf8gSBAg6OEN07NrAQzHOb05Jkcop6d1JDjzperVWyc/0GwVSZN+vx5Z1eBk6uVFffNSXduZvn1ykqv7a6rw/n+PDQK9Dzpwn+OqFv407uoMcORxPDYJBFb3KRXPnZNSmtbDQsAxbgoa5HDFmEELpQoDf3eWqFYG9LxS3fVSPTn0pyObx+hNXUFvKXdouYnGi19yHULVFWLCjGXSwL2OwXDOkQlPi4pOR73RlwU/T71qfzPmivVpcAYZrV+/c7ljL8vfGqVQpgOJRzo5fmI7NXd26FIHcf4O1NVeL763v0LTVGnTjutm2mdwZJbez6R6aIyDnzOIeXtZ4uiFwjnXaS4HKGRFvKHld4Q7SgjzDpj1I6OgQufh4/7mulFWnbjgZVVzDWW3OhHKR3bG7CrP0kJCD4y6WX1rMVtsl4aZgnCLFDV9xOiH/diSx2vIbP+zR4W0VXu/1xIrqVNGdodq7hjbUtvdbRPMqwvNnk2ymCtT/u7cNjYe74alHG2y8+8WBe/UGg=
  on:
    tags: true
    repo: limix/liknorm-py
    branch: master
    skip_existing: true
