language: python
python: 3.6
env:
  global:
  - PKG_NAME=liknorm
  - CIBW_SKIP="cp27-* cp34-* cp35-*"
  - CIBW_BEFORE_BUILD_LINUX="./before-build-linux"
  - CIBW_BEFORE_BUILD_MACOS="curl -O https://raw.githubusercontent.com/limix/liknorm/master/install && bash install"
matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx
      language: generic
      before_install:
        - brew update
        - brew outdated python || brew upgrade python
        - brew unlink python && brew link python
        - export PATH="/usr/local/opt/python/libexec/bin:$PATH"
        - hash -r
        - python -m pip install --upgrade pip setuptools wheel
addons:
  apt:
    packages:
    - libffi-dev
    - libffi6
    - cmake
install:
- bash <(curl -fsSL https://raw.githubusercontent.com/limix/liknorm/master/install)
script:
- |
  if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
    sudo mkdir -p /usr/local/man
    sudo chown -R "${USER}:admin" /usr/local/man
  fi
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis.sh)
- python -m pip install cibuildwheel>=0.9.2 pip2pi
- cibuildwheel --output-dir wheelhouse
- python -m pip uninstall $PKG_NAME -q || true
- |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    sudo rm -f /usr/local/include/liknorm.h
    sudo rm -f /usr/local/lib/libliknorm.so
    sudo rm -f /usr/local/lib/libliknorm_static.a
  fi
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    rm -f /usr/local/include/liknorm.h
    rm -f /usr/local/lib/libliknorm.dylib
    rm -f /usr/local/lib/libliknorm_static.a
  fi
- dir2pi wheelhouse/
- cd .. && python -m pip install $PKG_NAME --no-index --find-links file://$TRAVIS_BUILD_DIR/wheelhouse
- python -c "import $PKG_NAME; import sys; sys.exit($PKG_NAME.test())"
- cd $TRAVIS_BUILD_DIR
- |
  if [ "${TRAVIS_TAG:-}" != "" ]; then
    python -m pip install twine
    python -m twine upload --skip-existing wheelhouse/*
  fi
notifications:
  email:
    recipients:
    - danilo.horta@gmail.com
    on_success: never
    on_failure: always
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: fMasPDnDnJOgzbgS+UcNTvykBhTQxsAXm2aCdSB1W9XM3f98+Qlmd1w0jbDrljkCo+e1trnZDn+eW0fW4h+oX7FdlwAM1ktOJVJJI1wNq/xai8q5a4NAtY/us8OKF5sg2UfyuuPXm6P4dhdW9minbTJ3bmh+n7IftrVYwFf8gSBAg6OEN07NrAQzHOb05Jkcop6d1JDjzperVWyc/0GwVSZN+vx5Z1eBk6uVFffNSXduZvn1ykqv7a6rw/n+PDQK9Dzpwn+OqFv407uoMcORxPDYJBFb3KRXPnZNSmtbDQsAxbgoa5HDFmEELpQoDf3eWqFYG9LxS3fVSPTn0pyObx+hNXUFvKXdouYnGi19yHULVFWLCjGXSwL2OwXDOkQlPi4pOR73RlwU/T71qfzPmivVpcAYZrV+/c7ljL8vfGqVQpgOJRzo5fmI7NXd26FIHcf4O1NVeL763v0LTVGnTjutm2mdwZJbez6R6aIyDnzOIeXtZ4uiFwjnXaS4HKGRFvKHld4Q7SgjzDpj1I6OgQufh4/7mulFWnbjgZVVzDWW3OhHKR3bG7CrP0kJCD4y6WX1rMVtsl4aZgnCLFDV9xOiH/diSx2vIbP+zR4W0VXu/1xIrqVNGdodq7hjbUtvdbRPMqwvNnk2ymCtT/u7cNjYe74alHG2y8+8WBe/UGg=
  on:
    tags: true
    repo: limix/liknorm-py
    branch: master
    python: 3.6
