name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-10.15]

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.10.0

      - name: Install dependencies
        run: /bin/bash -c ci/install-deps
        shell: bash

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_SKIP: "pp* cp27-* cp34-* cp35-* cp36-* *_i686 *-win32"
          CIBW_BEFORE_BUILD_LINUX: "{project}/ci/linux-deps"
          CIBW_BEFORE_BUILD_MACOS: "{project}/ci/macos-deps"
          CIBW_BEFORE_BUILD_WINDOWS: "bash {project}/ci/windows-deps"
          CIBW_TEST_COMMAND: "bash {project}/ci/test"

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
